AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: Python SAM Application

Globals:
  Function:
    Timeout: 3

Resources:
  ReturnCertExpiryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: return_cert_expiry/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        ReturnCertExpiry:
          Type: Api
          Properties:
            Path: /certchecker
            Method: get

Outputs:
  ReturnCertExpiry:
    Description: "API Gateway endpoint URL for Prod stage for Return Cert Expiry function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ReturnCertExpiryFunction:
    Description: "Return Cert Expiry Lambda Function ARN"
    Value: !GetAtt ReturnCertExpiryFunction.Arn
  ReturnCertExpiryFunctionIamRole:
    Description: "Implicit IAM Role created for Return Cert Expiry function"
    Value: !GetAtt ReturnCertExpiryFunctionRole.Arn
